spring.application.name: api-gateway

server.port: 8080

#eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

jwt.secretKey: asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Apply to all routes
            allowedOrigins:
              - http://localhost:9090 # Your React frontend
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: user-oauth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/oauth2/**

        - id: post-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

#        - id: user-profile
#          uri: lb://USER-PROFILE
#          predicates:
#            - Path=/api/v1/profile/**
#          filters:
#            - StripPrefix=2
#            - name: AuthenticationFilter


